/*
 http://i2tmlabs.com/license.html
 @namespace
 @name CS2I
*/
(function(){var a={camelize:function(){return this.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()})},contains:function(a){a="string"===typeof a?a:a.toString();return-1<this.indexOf(a)},count:function(a){"[object RegExp]"!==Object.prototype.toString.call(a)&&a.toString().replace(/\$\^\[\]\{\}\(\)\?\:\.\+\*/g,"\\$1");return(this.match(what)||[]).length},enclose:function(a,b){return(a=a||"")+this+(b?b:a)},extract:function(a,b){b=void 0===b?0:b;if(!a.global)return this.match(a)[b]||"";for(var f,
g=[];f=a.exec(this);)g[g.length]=f[b]||"";return g},forEach:function(a){for(var b,f=-1;b=this[++f];)a.call(this,b,f);return!0},forEachWord:function(a){var b=this,f=-1;b.replace(/\b([\w\-]+)\b/g,function(g,h){a.call(b,h,++f);return g});return!0},linkify:function(a){return this.replace(/(^|\s)((?:f|ht)tps?:\/\/[^\s]+)/g,a||'$1<a href="$2">$2</a>')},many:function(a){return Array(a?a+1:2).join(this)},randomize:function(){return this.split("").sort(function(){return 0.5<Math.random()?-1:1}).join("")},
remove:function(a){return this.replace(a||/./g,"")},reverse:function(){return this.split("").reverse().join("")},shorten:function(a,b){var f=this.substring(0,a||this.length);return f+(f===this?"":b||"")},sort:function(){return Array.prototype.sort.apply(this.split(""),arguments).join("")},toDOM:function(){document.createElement("div").innerHTML=this;return Array.prototype.slice.call(div.childNodes)},trim:function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},wrap:function(a,b,f){b=b||"\n";
a=a||75;return this?this.match(RegExp(".{1,"+a+"}(\\s|$)"+(f?"|.{"+a+"}|.+$":"|\\S+?(\\s|$)"),"g")).join(b):this}},b;for(b in a)String.prototype[b]=String.prototype[b]||a[b]})();RUN=function(a){this.vld(nldr.bootstrap)&&r2wl.applets.use({file:a})};
ISA=function(a){what=function(a){return Object.prototype.toString.call(a).replace("[","").replace("]","").split(" ").pop()};kind=function(a,c){if(null===c)return"null";if("undefined"===c)return"undefined";if("Object"!==a&&"Function"!==a)return a;if("Object"===a)return"undefined"!==typeof c.constructor?"undefined"!==typeof c.Class?"undefined"!==typeof c.Class._CLASSNAME?c.Class._CLASSNAME:"undefined"!==typeof c.name&&""!==c.name?"Object:"+c.name:"Object:Unnamed":"Object:Simple":"undefined"!==typeof c.toString?
a:"Object";if("Function"===a&&"undefined"!==typeof c.arguments)return"undefined"!==typeof c.prototype?"undefined"!==typeof c.name&&""!==c.name?"Method:"+c.name:"Method:Unnamed":a};return kind(what(a),a)};
extend("I$Interface","I$Device",{maxTotalObjects:0,pixelRatio:0,isiPhone:!1,isiPhone4:!1,isiPad:!1,isiPod:!1,isAndroid:!1,isTouch:!1,isFirefox:!1,isChrome:!1,isOpera:!1,isIE:!1,ieVersion:0,requestAnimFrame:null,hasMemoryProfiling:!1,canPlayOgg:!1,canPlayMP3:!1,canPlayWav:!1,init:function(){this.pixelRatio=window.devicePixelRatio||1;this.isiPhone=-1!=navigator.userAgent.toLowerCase().indexOf("iphone");this.isiPod=-1!=navigator.userAgent.toLowerCase().indexOf("ipod");this.isiPhone4=2==this.pixelRatio&&
this.isiPhone;this.isiPad=-1!=navigator.userAgent.toLowerCase().indexOf("ipad");this.isAndroid=-1!=navigator.userAgent.toLowerCase().indexOf("android");this.isFirefox=-1!=navigator.userAgent.toLowerCase().indexOf("firefox");this.isChrome=-1!=navigator.userAgent.toLowerCase().indexOf("chrome");this.isOpera=-1!=navigator.userAgent.toLowerCase().indexOf("opera");this.isTouch="undefined"!==window.ontouchstart;this.isiOS=this.isiPhone||this.iPad||this.isiPod;void 0!=window.performance&&(this.hasMemoryProfiling=
window.performance.memory);/MSIE (\d+\.\d+);/.test(navigator.userAgent)&&(this.ieVersion=new Number(RegExp.$1),this.isIE=!0);var a=new Audio;a.canPlayType("audio/ogg")&&(this.canPlayOgg=!0);a.canPlayType("audio/mpeg")&&(this.canPlayMP3=!0);a.canPlayType("audio/x-wav")&&(this.canPlayWav=!0);this.requestAnimFrame=function(){var a=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a,
b){window.setTimeout(a,16,Date.now())};return function(c,e){a.apply(window,[c,e])}}()},canPlay:function(a){return"mp3"===a.toLowerCase()&&this.canPlayMP3||"ogg"===a.toLowerCase()&&this.canPlayOgg||"wav"===a.toLowerCase()&&this.canPlayWav?!0:!1},getUsedHeap:function(){return this.hasMemoryProfiling?window.performance.memory.usedJSHeapSize:0},getTotalHeap:function(){return this.hasMemoryProfiling?window.performance.memory.totalJSHeapSize:0}},{},{},[]);
extend("I$Interface","I$HashList",{},{hashtable:null,init:function(){this.hashtable=create("I$Hashtable")},add:function(a,b){var c=this.hastable.get(a);null==c&&(c=create("LinkedList"),this.hastable.put(a,c));c.add(b)},remove:function(a,b){var c=this.hastable.get(a);if(null==c)throw"No list for a key in hashlist when removing";c.remove(b)},get:function(a){return this.hastable.get(a)}},{},[]);
P$.interfaces.Classes.Hashtable=function(){function a(b){if("string"==typeof b)return b;if(typeof b.hashCode==p)return b=b.hashCode(),"string"==typeof b?b:a(b);if(typeof b.toString==p)return b.toString();try{return String(b)}catch(c){return Object.prototype.toString.call(b)}}function b(a,b){return a.equals(b)}function c(a,b){return typeof b.equals==p?b.equals(a):a===b}function e(a){return function(b){if(null===b)throw Error("null is not a valid "+a);if("undefined"==typeof b)throw Error(a+" must not be undefined");
}}function f(a,b,c,e){this[0]=a;this.entries=[];this.add.Entry(b,c);null!==e&&(this.getEqualityFunction=function(){return e})}function g(a){return function(b){for(var c=this.entries.length,e,f=this.getEqualityFunction(b);c--;)if(e=this.entries[c],f(b,e[0]))switch(a){case n:return!0;case s:return e;case u:return[c,e[1]]}return!1}}function h(a){return function(b){for(var c=b.length,e=0,f=this.entries.length;e<f;++e)b[c+e]=this.entries[e][a]}}function k(a,b){var c=a[b];return c&&c instanceof f?c:null}
function q(b,c){var e=this,g=[],h={},n=typeof b==p?b:a,s=typeof c==p?c:null;this.put=function(a,b){m(a);l(b);var c=n(a),e,r=null;(e=k(h,c))?(c=e.getEntryForKey(a))?(r=c[1],c[1]=b):e.addEntry(a,b):(e=new f(c,a,b,s),g[g.length]=e,h[c]=e);return r};this.get=function(a){m(a);var b=n(a);if(b=k(h,b))if(a=b.getEntryForKey(a))return a[1];return null};this.containsKey=function(a){m(a);var b=n(a);return(b=k(h,b))?b.containsKey(a):!1};this.containsValue=function(a){l(a);for(var b=g.length;b--;)if(g[b].containsValue(a))return!0;
return!1};this.clear=function(){g.length=0;h={}};this.isEmpty=function(){return!g.length};var t=function(a){return function(){for(var b=[],c=g.length;c--;)g[c][a](b);return b}};this.keys=t("keys");this.values=t("values");this.entries=t("getEntries");this.remove=function(a){m(a);var b=n(a),c=null,e=k(h,b);if(e&&(c=e.removeEntryForKey(a),null!==c&&!e.entries.length)){a:{for(a=g.length;a--;)if(e=g[a],b===e[0])break a;a=null}v(g,a);delete h[b]}return c};this.size=function(){for(var a=0,b=g.length;b--;)a+=
g[b].entries.length;return a};this.each=function(a){for(var b=e.entries(),c=b.length,f;c--;)f=b[c],a(f[0],f[1])};this.putAll=function(a,b){for(var c=a.entries(),f,g,h,r=c.length,k=typeof b==p;r--;)f=c[r],g=f[0],f=f[1],k&&(h=e.get(g))&&(f=b(g,h,f)),e.put(g,f)};this.clone=function(){var a=new q(b,c);a.putAll(e);return a};this.toString=function(){for(var a="",b=this.keys(),c=0;c<b.length;c++)var e=this.get(b[c]),a=a+(b[c].toString()+" = "+e.toString()+"\n");return a}}var p="function",v=typeof Array.prototype.splice==
p?function(a,b){a.splice(b,1)}:function(a,b){var c,e,f;if(b===a.length-1)a.length=b;else for(c=a.slice(b+1),a.length=b,e=0,f=c.length;e<f;++e)a[b+e]=c[e]},m=e("key"),l=e("value"),n=0,s=1,u=2;f.prototype={getEqualityFunction:function(a){return typeof a.equals==p?b:c},getEntryForKey:g(s),getEntryAndIndexForKey:g(u),removeEntryForKey:function(a){return(a=this.getEntryAndIndexForKey(a))?(v(this.entries,a[0]),a[1]):null},addEntry:function(a,b){this.entries[this.entries.length]=[a,b]},keys:h(0),values:h(1),
getEntries:function(a){for(var b=a.length,c=0,e=this.entries.length;c<e;++c)a[b+c]=this.entries[c].slice(0)},containsKey:g(n),containsValue:function(a){for(var b=this.entries.length;b--;)if(a===this.entries[b][1])return!0;return!1}};return q}();extend("I$Interface","I$LinkedListNode",{},{obj:null,nextLinked:null,prevLinked:null,free:!0,next:function(){return this.nextLinked},object:function(){return this.obj},prev:function(){return this.prevLinked}},{},[]);
extend("I$Interface","I$LinkedList",{},{first:null,last:null,count:0,objToNodeMap:null,init:function(){this._super();this.objToNodeMap=P$.create("Hashtable")},getNode:function(a){return this.objToNodeMap.get(a.getUniqueId())},addNode:function(a){var b=new CS2I.LinkedNode;b.obj=a;b.prevLinked=null;b.nextLinked=null;b.free=!1;this.objToNodeMap.put(a.getUniqueId(),b);return b},add:function(a){var b=this.getNode(a);if(null==b)b=this.addNode(a);else{if(!1==b.free)throw"Attempting to add object: "+a.getUniqueId()+
" twice to list "+this.getUniqueId();b.obj=a;b.free=!1;b.nextLinked=null;b.prevLinked=null}if(null==this.first)this.last=this.first=b,b.nextLinked=null,b.prevLinked=null;else{if(null==this.last)throw"Hmm, no last in the list -- that shouldn't happen here";this.last.nextLinked=b;b.prevLinked=this.last;this.last=b;b.nextLinked=null}this.count++},has:function(a){a=this.getNode(a);return!(null==a||!0==a.free)},moveUp:function(a){this.dump("before move up");a=this.getNode(a);if(!a)throw"Oops, trying to move an object that isn't in the list";
if(null!=a.prevLinked){var b=a.prevLinked,c=b.prevLinked;a==this.last&&(this.last=b);var e=a.nextLinked;c&&(c.nextLinked=a);a.nextLinked=b;a.prevLinked=b.prevLinked;b.nextLinked=e;b.prevLinked=a;this.first==b&&(this.first=a)}},moveDown:function(a){a=this.getNode(a);if(!a)throw"Oops, trying to move an object that isn't in the list";if(null!=a.nextLinked){var b=a.nextLinked;this.moveUp(b.obj);this.last==b&&(this.last=a)}},sort:function(a){for(var b=[],c=this.first;c;)b.push(c.obj.ect()),c=c.next();
this.clear();b.sort(a);for(a=0;a<b.length;a++)this.add(b[a])},remove:function(a){a=this.getNode(a);if(null==a||!0==a.free)return!1;null!=a.prevLinked&&(a.prevLinked.nextLinked=a.nextLinked);null!=a.nextLinked&&(a.nextLinked.prevLinked=a.prevLinked);null==a.prevLinked&&(this.first=a.nextLinked);null==a.nextLinked&&(this.last=a.prevLinked);a.free=!0;a.prevLinked=null;a.nextLinked=null;this.count--;return!0},clear:function(){for(var a=this.first;null!=a;)a.free=!0,a=a.nextLinked;this.first=null;this.count=
0},length:function(){return this.count},dump:function(a){for(a=this.first;null!=a;)a=a.next()}},{},[]);
extend("I$Interface","I$PerformanceMeasure",{history:[],clearHistory:function(){history.length=0}},{timeStart:0,timeEnd:0,timeDelat:0,memStart:0,memEnd:0,memDelta:0,description:null,init:function(a){this.description=a;this.start();this.Class.history.push(this)},start:function(){this.timeStart=Date.now();this.memStart=CS2I.Device.getUsedHeap()},end:function(){this.timeEnd=Date.now();this.timeDelta=this.timeEnd-this.timeStart;this.memEnd=CS2I.Device.getUsedHeap();this.memDelta=this.memEnd<this.memStart?
0:this.memEnd-this.memStart;return this.toString()},toString:function(){return this.description+" took "+this.timeDelta+"ms, "+(0==this.memDelta?"unknown":this.memDelta)+" byte(s)"}},{},[]);
extend("I$Interface","I$Pool",{INITIAL_POOL_SIZE:1,pools:new P$.interfaces.Classes.Hashtable,totalPooled:0,totalUsed:0,acquire:function(a){var b=this.getPool(a);if(void 0==b||null==b)b=new CS2I.Pool(a,this.INITIAL_POOL_SIZE),this.pools.put(a.fullName,b);return b.acquire()},release:function(a){var b=this.pools.get(a.Class.fullName);if(void 0==b)throw"Oops, trying to release an object of type "+a.Class.fullName+" but no pool exists. Did you new an object instead of using create.";b.release(a)},getPool:function(a){return this.pools.get(a.fullName)},
getStats:function(){for(var a="",b=this.pools.keys(),c=0;c<b.length;c++)var e=b[c],f=this.pools.get(e),a=a+(e+": "+f.getStats()+"\n");return a}},{freeList:null,expansion:1,traces:null,init:function(a,b){this._super();this.classType=a;this.freeList=[];this.expand(b)},startTracing:function(){this.tracing||(this.tracing=!0,this.traces?this.traces.clear():this.traces=new CS2I.Hashtable)},stopTracing:function(){this.tracing=!1},expand:function(a){CS2I.Pool.totalPooled+=a;for(var b=0;b<a;b++)this.freeList.push(new this.classType)},
getFreeCount:function(){return this.freeList.length},acquire:function(){0>=this.freeList.length&&(this.expansion=Math.round(1.2*this.expansion)+1,this.expand(this.expansion));return this.freeList.pop()},release:function(a){this.freeList.push(a)},getStats:function(){var a=this.Class.fullName+" stats: "+this.freeList.length+" free.";if(this.tracing){var a=a+"TRACING\n",b=this.traces.keys(),c;for(c in b)a+=b[c]+" ("+this.traces.get(b[c]).value+")\n"}return a},dump:function(a){this.info("================== "+
a+" ===================");this.info("FREE");this.freeList.dump()},size:function(){return this.freeList.length},getFreeList:function(){return this.freeList}},{},[]);
extend("I$Pool","I$DualPool",{acquire:function(a){var b=this.getPool(a);if(void 0==b||null==b)b=new CS2I.DualPool(a,this.INITIAL_POOL_SIZE),this.pools.put(a.fullName,b);return b.acquire()},getStats:function(){for(var a="",b=this.pools.keys(),c=0;c<b.length;c++)var e=b[c],f=this.pools.get(e),a=a+(e+" (free: "+f.freeList.length()+" used: "+f.usedList.length()+")\n");return a}},{freeList:null,usedList:null,init:function(a,b){this.classType=a;this.usedList=new CS2I.LinkedList;this.freeList=new CS2I.LinkedList;
this.expand(b)},expand:function(a){CS2I.Pool.totalPooled+=a;for(var b=0;b<a;b++)this.freeList.add(new this.classType)},returnObj:null,acquire:function(){null==this.freeList.first&&this.expand(Math.round(this.size()/5)+1);this.returnObj=this.freeList.first.obj;this.freeList.remove(this.returnObj);this.returnObj.destroyed=!1;this.usedList.add(this.returnObj);return this.returnObj},release:function(a){this.freeList.add(a);this.usedList.remove(a)},dump:function(a){this.info("================== "+a+" ===================");
this.info("FREE");this.freeList.dump();this.info("USED");this.usedList.dump()},size:function(){return this.freeList.count+this.usedList.count},getUsedList:function(){return this.usedList}},{},[]);extend("I$Interface","I$Pooled",{create:function(){return CS2I.Pool.acquire(this)},getPool:function(){return CS2I.Pool.getPool(this)}},{destroyed:!1,init:function(){this._super()},release:function(){this.onRelease();CS2I.Pool.release(this)},onRelease:function(){}},{},[]);
extend("I$Interface","I$DualPooled",{create:function(){return CS2I.DualPool.acquire(this)},getPool:function(){return CS2I.DualPool.getPool(this)}},{destroyed:!1,init:function(){this._super()},release:function(){this.onRelease();CS2I.DualPool.release(this)},onRelease:function(){}},{},[]);
Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be fBound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,e=function(){},f=function(){return c.apply(this instanceof e?this:a||window,b.concat(Array.prototype.slice.call(arguments)))};e.prototype=this.prototype;f.prototype=new e;return f});
Array.prototype.indexOf||(Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var e=0;0<arguments.length&&(e=Number(arguments[1]),e!=e?e=0:0!=e&&Infinity!=e&&-Infinity!=e&&(e=(0<e||-1)*Math.floor(Math.abs(e))));if(e>=c)return-1;for(e=0<=e?e:Math.max(c-Math.abs(e),0);e<c;e++)if(e in b&&b[e]===a)return e;return-1});
extend("I$Interface","I$AccuTimer",{timer:null,create:function(a,b,c,e){function f(){if(k++>=g)e(g,k);else{c(g,k,b);var a=(new Date).getTime()-q-k*h;this.timer=setTimeout(f,h-a)}}0>=a&&(a=864E5);0>=b&&(b=1);var g=a/100*(b/10),h=a/g,k=0,q=(new Date).getTime();this.timer=setTimeout(f,h)},CallMebackIn:function(a,b){if(this.vld(b))return window.setTimeout(b,a)}},{},{},[]);
extend("I$Pooled","I$FactoryWorker",{maxTotalObjects:0,_lastUsed:0,create:function(a){var b=this._super();return b.parse(a)?b:b.name}},{},{},[]);
extend("I$Interface","I$Factory",{maxTotalObjects:0},{onChanged:function(){},objects:{},idleLifeSpan:0,count:0,init:function(a,b){this._super();M$.chk(a,"Undefined Factory");M$.chk(b,0);this.factoryType=a;this.setLife(b)},setLife:function(a){a*=1E3;this.idleLifeSpan!=a&&(this.idleLifeSpan=a)},create:function(){},add:function(a,b){if(this.vld(b)){if("function"===typeof this.onChanged)this.onChanged({name:a,action:"Added"});this.objects[a]=b;this.count++;return this.objects[a]}},remove:function(a){if(this.exists(a))try{if("function"===
typeof this.onChanged)this.onChanged({name:a,action:"Removed"});delete this.objects[a];this.count--;0>this.count&&(this.count=0)}catch(b){return!1}},exists:function(a){this.objects.hasOwnProperty(a);return!0},use:function(a){null!=typeof a&&"object"===typeof a?a=this.exists(a.name)?this.objects[a.name]:this.create(a):(this.info("Factory::use(object) - No longer takes 2 params, use object format."),a=null);return a}},{},[]);
extend("I$Interface","I$DeviceStorage",{maxTotalObjects:0,supported:null,config:null,create:function(a,b){this.config=a;this._addMethods(this);return this._prepare(b)?this.prototype:!1},_addMethods:function(a){Storage.prototype.setObject=function(a,c){var e=JSON.stringify(c);this.setItem(a,e)};Storage.prototype.getObject=function(b){b=this.getItem(b);if(a.vld(b))return $tmp2=JSON.parse(b)}},setup:function(a){"String"===ISA(a)&&(this.vld(this.prototype.data[a])||(this.prototype.data[a]={}),this.vld(this.prototype.data[a].cfg)||
(this.prototype.data[a].cfg={}),this.vld(this.prototype.data[a].files)||(this.prototype.data[a].files={}))},isSupported:function(){if(!0===this.prototype.supported||!1===this.prototype.supported)return this.prototype.supported;var a="Checking for Local Storage Support...";"undefined"!==typeof Storage?(a+="Supported.",this.prototype.supported=!0):(a+="Not Supported.",this.prototype.supported=!1);this.info(a);return this.prototype.supported},load:function(a){this.prototype.data.global=localStorage.getObject("global");
this.prototype.data[a]=localStorage.getObject(a);this.setup("global");this.setup(a)},remove:function(a){this.isSupported()&&($use=0===a?"global":this.config.name,localStorage.removeItem($use))},what_where:function(a){return 0===a?{where:"global",what:"cfg"}:1===a?{where:"global",what:"files"}:2===a?{where:this.config.name,what:"cfg"}:3===a?{where:this.config.name,what:"files"}:null},get:function(a,b){if(this.isSupported()){$use=this.what_where(b);try{if(a in this.prototype.data[$use.where][$use.what])return this.prototype.data[$use.where][$use.what][a]}catch(c){}}return null},
set:function(a,b,c){if(this.isSupported()){c=this.what_where(c);try{return this.prototype.data[c.where][c.what][a]=b,localStorage.setObject(c.where,this.prototype.data[c.where]),this.prototype.data[c.where][c.what][a]}catch(e){}}},_prepare:function(a){this.isSupported()&&(this.config.name=(new String(this.config.name.split(" ").join(""))).toLowerCase(),this.load(this.config.name),"firstVisit"in this.prototype.data.global.cfg||(this.set("firstVisit",!0,0),this.set("firstVisitTime",Date.now(),0)),"firstVisit"in
this.prototype.data[this.config.name].cfg||(this.set("firstVisit",!0,2),this.set("firstVisitTime",Date.now(),2)));return!0}},{data:{},init:function(){this._super()},removeGlobal:function(){this.Class.remove(0)},removeApp:function(){this.Class.remove(1)},getGlobalCfg:function(a){return this.Class.get(a,0)},setGlobalCfg:function(a,b){this.Class.set(a,b,0)},getGlobalFile:function(a){return this.Class.get(a,1)},setGlobalFile:function(a,b){this.Class.set(a,b,1)},getAppCfg:function(a){return this.Class.get(a,
2)},setAppCfg:function(a,b){this.Class.set(a,b,2)},getAppFile:function(a){},setAppFile:function(a,b){this.Class.set(a,b,3)}},{},[]);
extend("I$Interface","I$DeviceTest",{maxTotalObjects:1},{canvas:null,startTime:0,results:[],init:function(){this._super();this.canvas=M$.gei("testCanvas");return!0},log:function(a,b){var c=M$.gei("testLog");c.value+=a;b&&(c.value+="\n");c.scrollTop=c.scrollHeight},run:function(){var a=0,b=0,c=0,e=0,f=0;this.testScreen();if(this.testBrowser()){for(i=0;4>=i;i++)a=this.testDate(),b+=a;this.results.date=b/3;this.log("Date Test: "+this.results.date+"sec",!0);for(i=0;4>=i;i++)a=this.testPixels(),c+=a;this.results.pixels=
c/3;this.log("Pixel Test: "+this.results.pixels+"sec",!0);for(i=0;4>=i;i++)a=this.testMath(),e+=a;this.results.math=e/3;this.log("Math Test: "+this.results.math+"sec",!0);for(i=0;4>=i;i++)a=this.testMemory(),f+=a;this.results.mem=f/3;this.log("Memory Test: "+this.results.mem+"sec",!0)}this.log("Your performance index is: "+(this.results.date+this.results.pixels+this.results.math+this.results.mem)/4,!0)},startTimer:function(){this.startTime=new Date;return this.startTime=this.startTime.getTime()},
stopTimer:function(){var a=new Date,a=a.getTime();return a=(a-this.startTime)/1E3},testBrowser:function(){var a=navigator.userAgent.toLowerCase(),b;-1!=navigator.appVersion.indexOf("Win")&&(this.platform="Windows");-1!=navigator.appVersion.indexOf("Mac")&&(this.platform="MacOS");-1!=navigator.appVersion.indexOf("X11")&&(this.platform="UNIX");-1!=navigator.appVersion.indexOf("Linux")&&(this.platform="Linux");-1!=navigator.appVersion.indexOf("Android")&&(this.platform="Android");-1!=navigator.appVersion.indexOf("iOS")&&
(this.platform="iOS");this.log("Detected "+this.platform+" OS and ",!1);document.documentMode?(a.indexOf("msie"),this.browserCheck="IE",this.browserName="Internet Explorer",this.browserVersion=""+document.documentMode):-1<a.indexOf("chrome")?(b=a.indexOf("chrome"),this.browserCheck="Chrome",this.browserName="Google Chrome",this.browserVersion=""+parseFloat(""+a.substring(b+7))):-1<a.indexOf("firefox")?(b=a.indexOf("firefox"),this.browserCheck="Firefox",this.browserName="Mozilla Firefox",this.browserVersion=
""+parseFloat(""+a.substring(b+8))):-1<a.indexOf("minefield")?(b=a.indexOf("minefield"),this.browserCheck="Firefox",this.browserName="Mozilla Firefox Minefield",this.browserVersion=""+parseFloat(""+a.substring(b+10))):-1<a.indexOf("opera")?(this.browserName=this.browserCheck="Opera",this.browserVersion=""):-1<a.indexOf("safari")&&(b=a.indexOf("safari"),this.browserCheck="Safari",this.browserName="Apple Safari",this.browserVersion=""+parseFloat(""+a.substring(b+7)));this.log(this.browserName+" v"+
this.browserVersion+" Browser.",!1);if("Chrome"===this.browserCheck||"Firefox"===this.browserCheck||"Opera"===this.browserCheck)if("Chrome"===this.browserCheck&&30<=this.browserVersion||"Firefox"===this.browserCheck&&25<=this.browserVersion||"Opera"===this.browserCheck&&18<=this.browserVersion)return this.log("[Pass]",!0),!0;this.log("[Fail]",!0);return!1},testScreen:function(){this.log("Resolution is "+screen.width+"x"+screen.height+" - ",!1);var a=M$.gei("dpp"),a=window.getComputedStyle(a,null).getPropertyValue("font-size");
"3px"!==a&&(this.results.dppx="3px"===a?3:"2px"===a?2:"1.5px"===a?1.5:1);this.log(this.results.dppx+" dppx",!0)},testPixels:function(){var a=this.canvas.getContext("2d"),b=a.createImageData(1,1),c,e,f=b.data;this.canvas.width=this.canvas.width;this.startTimer();for(i=0;1E6>=i;i++)f[0]=Math.floor(255*Math.random()),f[1]=Math.floor(255*Math.random()),f[2]=Math.floor(255*Math.random()),f[3]=255,c=Math.floor(Math.random()*this.canvas.width),e=Math.floor(Math.random()*this.canvas.height),a.putImageData(b,
c,e);return this.stopTimer()},testDate:function(){this.startTimer();for(i=2E3;102E3>=i;i++)(new Date("Dec 24, "+i)).getDay();return this.stopTimer()},testMath:function(){this.startTimer();for(i=0;1E5>=i;i++)Math.random(),Math.random(),Math.random(),Math.random(),Math.random(),Math.random(),Math.random(),Math.random();return this.stopTimer()},testMemory:function(){var a=[],b={bool:!1,str:"A String",integer:1234,real:3.14159};this.startTimer();for(i=0;1E6>=i;i++)a.push(b);delete a;return this.stopTimer()}},
{},[]);
extend("I$Interface","I$Launcher",{maxTotalObjects:1,appPaused:!1,appRunning:!1,btnPlay:null,canvas:null,gameClass:null,gldlActive:!1,enableFS:function(){this.canvas&&!this.canvas.fullScreen&&(this.canvas.requestFullscreen?this.canvas.requestFullscreen():this.canvas.webkitRequestFullscreen?this.canvas.webkitRequestFullscreen():this.canvas.mozRequestFullScreen?this.canvas.mozRequestFullScreen():this.canvas.msRequestFullscreen&&this.canvas.msRequestFullscreen())},disableFS:function(){this.canvas&&this.canvas.fullScreen&&
(D$.exitFullscreen?D$.exitFullscreen():D$.mozCancelFullScreen?D$.mozCancelFullScreen():D$.webkitCancelFullScreen?D$.webkitCancelFullScreen():D$.msExitFullScreen&&D$.msExitFullScreen())}},{init:function(){this._super();this.test=create("I$DeviceTest")},getCanvas:function(){return this.Class.canvas},isActive:function(){return nldr.config.modules.gldl&&"undefined"!=typeof gldl?!0:!1},testOrientation:function(){this.Class.appPaused=window.innerWidth>window.innerHeight?!1:!0},dependentFiles:function(){if(M$.getDevMode())return nldr.addFile("i2tm/js/gldl.local.js"),
"src/class.ai.js src/class.enemy.js src/class.fighter.js src/class.weapon.js src/layer.game.js src/layer.hud.js src/layer.stars.js src/scene.game.js src/scene.loading.js src/scene.publisher.js src/system.prizedropper.js src/tools.js src/physics.js src/game.js".split(" ");nldr.addFile("i2tm/js/gldl.release.js");return["js/game.min.js"]},createGame:function(){this.vld(nldr.config.modules.gldl)&&nldr.que(this.dependentFiles(),!0)},onLoad:function(){gldl=create("I$GLDL");this.onLoaded();gldl.device.boot(this.getCanvas().id,
"TheGame");r2wl.launcher.play()},pauseGame:function(){this.isActive()&&(this.Class.btnPlay.textContent="Resume","undefined"!=typeof gldl.device.game&&gldl.device.game.pause(),M$.on("btnQuit"),M$.on("btnReset"),this.toggle("main",!0,!0),this.Class.appPaused=!0)},resumeGame:function(){this.isActive()&&("undefined"!=typeof gldl.device.game&&gldl.device.game.resume(),this.toggle("game",!0,!0),this.Class.appPaused=!1)},enableFullscreen:function(){this.Class.enableFS()},disableFullscreen:function(){this.Class.disableFS()},
reset:function(){this.isActive()&&(gldl.device.game.reset(),jQuery("#btnQuit").hide())},quit:function(){this.isActive()&&(r2wl.launcher.Class.btnPlay&&(M$.off("btnQuit"),M$.off("btnReset"),this.Class.btnPlay.textContent="Play"),this.disableFullscreen(),this.Class.appRunning=!1,this.Class.appPaused=!1,"undefined"!=typeof gldl.device&&"undefined"!=typeof gldl.device.game&&delete gldl.device.game,this.toggle("main",!0,!0))},play:function(){this.isActive()?this.vld(gldl.device.game)&&(this.Class.appPaused?
(this.enableFullscreen(),this.resumeGame()):(this.toggle("game",!0,!0),this.Class.canvas.width=screen.width,this.Class.canvas.height=screen.height,this.Class.canvas.style.width=this.Class.canvas.width+"px",this.Class.canvas.style.height=this.Class.canvas.height+"px",this.Class.canvas.style.background="black",this.enableFullscreen(),this.Class.appRunning=!1)):this.createGame()},toggle:function(a,b,c){a=a.toLowerCase();!0==c&&(M$.off("main"),M$.off("page_warning"),M$.off("page_game"),M$.off("page_loader"));
switch(a){case "body":if(b)M$.on("body");else M$.off("body");break;case "main":if(b)M$.on("main");else M$.off("main");break;case "warning":if(b)M$.on("page_warning");else M$.off("page_warning");break;case "game":if(b)M$.on("page_game");else M$.off("page_game")}},onLoaded:function(){var a=r2wl.launcher;GLDL&&nldr.config.modules.gldl&&this.info("Game Mode Detected...");this.isActive()&&(a.Class.btnPlay||(a.Class.btnPlay=M$.gei("btnPlay"),a.Class.btnPlay.innerHTML="Play"),a.Class.canvas||(a.Class.canvas=
M$.gei("page_game"),a.Class.canvas.allowfullscreen=!0),a.quit(),window.addEventListener("orientationchange",function(){a.testOrientation()},!1),window.addEventListener("resize",function(){a.testOrientation()},!1),a.testOrientation(),r2wl.redraw());a.toggle("main",!0,!1)}},{},[]);
extend("I$Interface","I$Google",{maxTotalObjects:0},{$enabled:!1,$loaded:!1,$analyticsLoaded:!1,$adSenseLoaded:!1,$version:"",$domain:null,$gaJsHost:null,$resizeTimer:null,config:{analytics:{trackingId:"",pageviews:!0,clicks:!0},ads:{clientId:"",ads:{}}},parent:null,init:function(a,b){this._super();this.parent=a;this.config=b;try{var c={};"object"==typeof b&&(""===this.config.analytics.trackingid&&this.warn("You did not set your Google Unique ID in the config file."),this.enabled=!0)}catch(e){this.error(e,
c,Array.prototype.slice.call(arguments,0))}},ga:function(a,b,c,e,f,g,h){this.$analyticsLoaded&&window.ga(a,b,c,e,f,g,h)},push:function(){if(this.$adSenseLoaded){var a={};this.info("Google Push.");try{(adsbygoogle=window.adsbygoogle||[]).push({})}catch(b){this.error(b,a,Array.prototype.slice.call(arguments,0))}}else ads=$(".adsbygoogle").css("background","#333")},connect:function(){if(this.$analyticsLoaded){var a={};try{window.ga("_setAccount",this.config.analytics.trackingid),window.ga("_setDomainName",
document.location.host),window.ga("_addIgnoredOrganic",document.location.host),window.ga("_trackPageview")}catch(b){this.error(b,a,Array.prototype.slice.call(arguments,0))}}},remove:function(a){if(this.$adSenseLoaded){var b=gec("adsbygoogle");if(0<b.length){for(i=0;i<b.length-1;i++)b[i].style.display="none",b[i].style.width="initial",b[i].removeAttribute("data-adsbygoogle-status"),b[i].removeAttribute("data-ad-slot");a&&setTimeout(this.parent.google.insert(),1E3)}}},insert:function(){getAds=function(a,
b){if("object"==typeof a.ads[b])return $.map(a.ads[b],function(a,b){return[a]})};try{var a={ads:0,slots:0,abg:M$.gec("adsbygoogle"),result:!1};a.slots=this.vld(a.abg)?a.abg:[];if(0<a.slots.length){a.ads=getAds(this.config,this.config.app.theme);for(i=0;i<a.ads.length;i++)a.slots[i].style.display="block",M$.esa(a.slots[i],"data-ad-client",this.config.ads.clientId),M$.esa(a.slots[i],"data-ad-slot",a.ads[i]),M$.esa(a.slots[i],"data-ad-format","auto"),this.push();this.$adSenseLoaded=!1;a.result=!0}else this.enabled=
!1}catch(b){this.error(b,a,Array.prototype.slice.call(arguments,0)),this.enabled=!1,a.result=!1}return a.result},delay:function(){this.$adSenseLoaded=!1;this.resizeTimer=setTimeout(function(){this.parent.google.$adSenseLoaded=!0;window.clearTimeout(this.parent.google.resizeTimer)},3E4)},load:function(){this.enabled&&(this.config.analytics&&this.parent.addFile("analytics.js","google","vendor"),this.config.ads&&this.parent.addFile("adsbygoogle.js","google","vendor"))},check:function(){this.$analyticsLoaded=
null!=M$.gei("analytics.js")?!0:!1;this.$adSenseLoaded=null!=M$.gei("adsbygoogle.js")?!0:!1},loaded:function(){this.enabled&&(this.check(),!0==this.$analyticsLoaded&&this.connect(),!0==this.$adSenseLoaded&&this.insert())},onResize:function(){}},{},[]);
extend("I$Pooled","I$Applet",{maxTotalObjects:0,params:{required:["role","name","version","uuid"],optional:["author","copyright","shared","scale"]},create:function(a,b){var c=this._super();return c.parse(data,b)?c:c.name}},{State:{QUEUED:0,LOADING:1,READY:2,ACTIVE:3,FAILED:4},header:{role:"applet",name:"default",version:"0.0.0",description:"",uuid:"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",publisher:"",author:"",copyright:"2014 by {YOU} - All rights reserved.",style:"",script:"",html:"",onload:null,onunload:null},
uri:"",id:"{AUTOSET}",state:-1,init:function(a){this._super();a=a[0];try{this.makeURI(a)&&this.setState(0)}catch(b){this.error(b,{},Array.prototype.slice.call(arguments,0))}},setState:function(a){if(0>a||4<a)this.warn("Invalid State [QUEUED:0, LOADING:1, READY:2, FAILED:3]");else if(this.state!=a)switch(this.state=a,this.state){case this.State.LOADING:this.fetch();break;case this.State.READY:this.embed()}},makeURI:function(a){var b={path:null,fileName:null,ext:null};try{this.header.name=this.vld(a.dataset.applet)?
a.dataset.applet:!1;this.header.role=this.vld(a.dataset.role)?a.dataset.role:"content";this.header.local=this.vld(a.dataset.local)&&"no"!=a.dataset.local?!0:!1;this.header.publisher=this.vld(a.dataset.publisher)?a.dataset.publisher:"";this.header.local=""==this.header.publisher?1:0;this.id=this.header.name;if(!this.header.name||!this.header.role)return this.setState(this.state.FAILED),!1;b.ext=".html";b.fileName="applet."+this.header.name+b.ext;if(!this.vld(b.path=nldr.getPath("applets","publisher")))return this.warn("Publisher path not found."),
!1;this.uri=b.path+b.fileName;return!0}catch(c){this.error(c,b,Array.prototype.slice.call(arguments,0))}return!1},pack:function(){getFunc=function(a){a=a.toString();return a.slice(a.indexOf("{")+1,a.lastIndexOf("}"))};var a={obj:null,hdr:null};a.obj=this.header;a.hdr="applet"===a.obj.role?"~A|":"~L|";try{return a.obj=JSON.stringify(this.header),a.obj=$m.pf.lzw.enc(a.obj),a.obj=a.hdr+a.obj,console.log(_obj.name+"->"+a.obj),a.obj}catch(b){this.error(b,a,Array.prototype.slice.call(arguments,0))}return!1},
unpack:function(a){setFunc=function(a,b){this[a]=b};var b={obj:null,hdr:""};try{if(b.hdr=a.substring(0,3),"~A|"==b.hdr||"~L|"==b.hdr){b.obj=a.substring(3,a.length);b.obj=$m.pf.lzw.dec(b.obj);this.header=JSON.parse(b.obj);if(b.obj.publisher&&b.obj.name&&b.obj.role&&b.obj.local)return b.obj;this.warn("Valid object with invalid properies. Discarding.")}else this.warn("Not a valid compiled Applet or Layout data.")}catch(c){this.error(c,b,Array.prototype.slice.call(arguments,0))}return!1},embed:function(){if(this.onShow)this.onShow();
this.header.script&&0<this.header.script.text.length&&M$.gei("tail").appendChild(this.header.script);this.header.style&&0<this.header.style.textContent.length&&M$.get("head")[0].appendChild(this.header.style);$("div[data-applet='"+this.header.name+"']").append(this.header.html)[0].id=this.id;this.setState(3)},unbed:function(){if(this.active){this.onUnloaded();this.active=!1;if(this.onHide)this.onHide();$a=M$.get("head")[0];$a.removeChild(this.header.name+"_script");$a.removeChild(this.header.name+
"_style")}},fetch:function(){var a={msg:null,fromLocal:!1,applet:null};try{a.msg="Received request for: "+this.header.name+"... ";a.applet=r2wl.local.getAppFile(this.header.name);this.vld(a.applet)&&(a.msg+="Found in local Storage.",this.onLoad(a.applet),a.fromlocal=!0);try{a.msg+="Requesting from via AJAX.",M$.xhr(this.uri,this._onLoad.bind(this),this._onError.bind(this),"get",null,!1)}catch(b){this.error(b,a,Array.prototype.slice.call(arguments,0))}}catch(c){this.error(c,a,Array.prototype.slice.call(arguments,
0))}},setDraggable:function(){$(function(){$("#wrapper").on("mousedown","div",function(){!0===this.draggable?($(this).addClass("draggable"),$(this).addClass("dragging").parents().on("mousemove",function(a){$(".dragging").offset({top:a.pageY-$(".dragging").outerHeight()/2,left:a.pageX-$(".dragging").outerWidth()/2}).on("mouseup",function(){$(this).removeClass("dragging")});"undefined"!=typeof a&&a.preventDefault()})):($(".draggable").removeClass("draggable"),$(this).removeClass("dragging"))}).on("mouseup",
function(){$(".draggable").removeClass("draggable")})})},htmlToApplet:function(a){var b={div:null};try{return b.div=window.document.createElement("div"),b.div.innerHTML=a,b.div.firstChild}catch(c){this.error(c,b,Array.prototype.slice.call(arguments,0))}},onLoaded:function(){this.loaded=!0;$evt=this.header.name+"_onload";"function"===typeof window.$evt&&window.$evt()},onUnLoaded:function(){this.unload=!0;$evt=this.header.name+"_onload";"function"===typeof window.$evt&&window.$evt()},_onLoad:function(a){if(!this.vld(a))return!1;
a=this.htmlToApplet(a);if("DIV"==a.tagName&&a.dataset.name){var b=r2wl.applets.objects[a.dataset.name],c=a;b.onLoaded();for(var e=0;3>e;e++)"STYLE"==c.children[e].tagName?(b.header.style=c.children[0],b.header.style.id=b.id+"_style"):"SCRIPT"==c.children[e].tagName?(b.header.script=c.children[1],b.header.script.id=b.id+"_script"):"DIV"==c.children[e].tagName&&(b.header.html=c.children[2].innerHTML);for(var f in c.dataset)b.header[f]=c.dataset[f];b.setState(2);r2wl.applets.scan(a.innerHTML,!1)}},_onError:function(a){this.warn("Error loading applet resource.")}},
{},[]);
extend("I$Factory","I$AppletFactory",{maxTotalObjects:0,_scanned:[],_active:[],_history:[],_loadQue:[]},{started:!1,finished:!1,_tracker:{failed:0,loading:0,loaded:0,fromConn:0,fromCache:0,loops:0,indexed:!1},init:function(){this._super("Applet")},create:function(a){var b={obj:null,attr:[]};try{b.obj=create("I$Applet",[a]),4===b.obj.state?delete b.obj:0===b.obj.state&&(this.add(b.obj.id,b.obj),b.obj.setState(1))}catch(c){this.error(c,b,Array.prototype.slice.call(arguments,0))}},add:function(a,b){this._super(a,
b);this.Class._scanned.push(a)},reset:function(){this.Class._loadQue=[];this._tracker={failed:0,loading:0,loaded:0,fromConn:0,fromCache:0,loops:0}},stop:function(){this.started=!1;this.finished=!0;this.reset()},start:function(){this.started||(this.started=!0,this.finished=!1,r2wl.ready=!1)},scan:function(a){a=this.getApplets(a,!1);for(var b=0;b<a.length;b++)div_i=a[b],this.create(a[b])},onHREFClick:function(a){try{r2wl.applets.setpage(this.name)}catch(b){ast(null,b.stack)}},onHREFHover:function(a){},
isActive:function(a){return"object"==typeof this.Class._active[a]?!0:!1},setpage:function(a){if(""!==a)try{var b=r2wl.applets.use({name:a});if(b){var c=this.getApplets("self");for(i=0;i<c.length;i++){var e=$(c[i]).attr("data-applet");r2wl.applets.use({name:e});$("div[data-applet='"+this.header.name+"']").append($html)}nldr.config.options.crossfade?"0"!=$("#main").css("opacity")&&(this.lastContent=M$.gei("main").innerHTML,$("#main").fadeOut(250,function(){M$.gei("main").innerHTML=b.html;$("#main").fadeIn(250,
"linear")})):(this.lastContent=M$.gei("main").innerHTML,M$.gei("main").innerHTML=b.html);r2wl.local.setAppCfg("currentPage",b.name)}}catch(f){ast(null,f.stack)}},scanAnchors:function(a){var b={};try{var c,e=0,f=0,g=0;a=this.vld(a)?$(a):$("body");if(""!=a[0].id&&(c=a[0].id,-1!=this.Class._scanned.indexOf(c)))return!0;var h=get("a");c=!1;for(i=0;i<h.length;i++)if(""!=h[i].hash){var k=h[i].hash.split(".");"#applet"==k[0]&&""!=k[1]&&(h[i].addEventListener("click",this.onHREFClick,!1),h[i].addEventListener("hover",
this.onHREFHover,!1),-1===this.Class._scanned.indexOf(k[1])?(c=""!=h[i].dataset.shared?!0:!1,this.Class._loadQue.push({name:k[1],shared:c}),this.Class._scanned.push(k[1]),g++):f++,h[i].name=k[1],e++)}return e}catch(q){this.error(q,b,Array.prototype.slice.call(arguments,0))}},getApplets:function(a,b){var c={role:null,roleName:null};try{var e=!1;c.role=!0==b||!1==b?b:!1;c.roleName=!0==b?"layout":"applet";"self"===a?(a=this.$html,e=!0):a=this.vld(a)?$(a):$("body");if(!this.vld(a))return 0;var f=$(a).find("div").filter(function(a){return void 0!==
$(this).data(c.roleName)});e&&0<f.length&&(this.hasChildren=!0);return f}catch(g){this.error(g,c,Array.prototype.slice.call(arguments,0))}return[]},findApplets:function(a,b){getAttributes=function(b,c,e,f){var g={};try{var m,l={};$el=M$.gei(e);m=M$.gda(e,1);$(c).find(e);if(!1!=m&&""!=m.applet)return l.name=e,l.target=typeof m.target==M$.db[0][7]?a.parentElement:m.target,null==l.target&&(l.target="body"),l.shared=typeof m.shared==M$.db[0][7]?"publisher":"shared",l.active=f,l.path=nldr.getPath("applets",
l.shared),b.Class._loadQue.push(l),l}catch(n){this.error(n,g,Array.prototype.slice.call(arguments,0))}};var c={};try{var e,f;a=this.vld(a)?a=$(a)[0]:a=get("body")[0];b=typeof b===M$.db[0][7]?0:1;e=this.getApplets(a);for(i=0;i<e.length;i++)""===e[i].id&&(e[i].id=e[i].dataset.applet),f=getAttributes(this,a,e[i].id,b),this.Class._active[e[i].dataset.applet]=f,e[i].style.display=b?"block":"none";this._tracker.loading=this.Class._loadQue.length}catch(g){this.error(g,c,Array.prototype.slice.call(arguments,
0))}},checkQue:function(){0<this.Class._loadQue.length&&!1==this.started&&this.start();if(0>=this.Class._loadQue.length){var a=r2wl.local.getAppCfg("currentPage");this.vld(a)?this.setpage(a):this.setpage(nldr.config.app.applet);return!0}2<this.Class._loadQue.length&&(a=this.Class._loadQue.filter(function(a,c){return r2wl.applets.Class._loadQue.indexOf(a)==c}),this.Class._loadQue=a);this._tracker.loading=this.Class._loadQue.length;this.requestApplet(this.Class._loadQue.shift());this._checkAllDone()},
requestApplet:function(a){var b={};try{if(!this.vld(a)||typeof a.target==M$.db[0][7])return!1;var c=!1,e=r2wl.local.getAppFile(a.name);this.vld(e)&&(this.onLoad(e),c=!0);var f=this.Class._history[a.name];if("undefined"!=typeof f){this._tracker.fromCache++;if(this.vld(f.div))this.onLoad(f.div);this.checkQue();return!0}if(""==a.name)return!1;this.Class._history[a.name]={name:a.name,src:nldr.getPath("applets",a.shared)+"applet."+a.name+".html",div:a.div};if(!c)try{M$.xhr(this.Class._history[a.name].src,
bnd(this,this.onLoad),bnd(this,this.onError),"get",null,!1)}catch(g){ast(g.stack)}}catch(h){this.error(h,b,Array.prototype.slice.call(arguments,0))}},_checkAllDone:function(){if(0>=this.Class._loadQue.length)return this.stop(),r2wl.ready=!0;this.checkQue();this._tracker.loops++;return this._tracker.loops>this._tracker.loading?!0:!1},onLoad:function(a){this._checkAllDone();if(!this.vld(a))return this.error("No data return from Ajax Request."),!1;var b;ISA(a);if("Object:Simple"===ISA(a)){b=!0;var c=
Applet.create(a,this.Class._active);$result=r2wl.applets.add(c.header.name,c)}else b=!1,c=$(a),c=Applet.create(a,this.isActive(c[0].dataset.name));this._tracker.loaded++;this._tracker.loading--;"object"===typeof c?(b&&c.header.name in this.Class._history&&"undefined"!==typeof this.Class._history[c.header.name].src&&(c.src=this.Class._history[c.header.name].src),this._tracker.fromConn++,this.scan(c.html),this.scanAnchors(c.html),$result=r2wl.applets.add(c.header.name,c),c.header.name==nldr.config.app.applet&&
r2wl.applets.setpage(c.header.name)):(this._tracker.failed++,delete this.Class._history[c],this.remove(c),this.warn("Unable to identify applet, discarding. [".toString(a)+"]"),$result=!1);return $result},onError:function(a){return null}},{},[]);
extend("I$Interface","I$ConfigManager",{maxTotalObjects:1,exposed:!1,path:{app:window.location.protocol+"//"+window.location.host+window.location.pathname.split("/").slice(0,-1).join("/")+"/",shared:"/content/shared/",publisher:"/content/",vendor:"/vendor/"},ready:!1,filesLoaded:!1,configLoaded:!1,_onSuccessCallback:null,_onFailedCallback:null,toString:function(){return"I$ConfigManager Class"}},{config:null,filesNeeded:null,init:function(a,b){this._super();this._onSuccessCallback=a;this._onFailedCallback=
b},setup:function(){this._super();this.config=M$.config},onReady:function(){this.config?this._onConfigSuccess(null):M$.xhr(this.getPath(null,"app")+"index.json",this._onConfigSuccess.bind(this),this._onConfigFailed.bind(this),"get",null,!1)},getPath:function(a,b,c){function e(a){return a.replace(/([~!@#$%^&*()_+=`{}\[\]\|\\:;'<>,.\/? ])+/g,"-").replace(/^(-)+|(-)+$/g,"")}var f=window.location.protocol+M$.db[2][0];c=c||!1;b=b||"nanofw";switch(b.toLowerCase()){case "home":return f;case "app":return this.Class.path.app;
case "vendor":f+=this.Class.path.vendor;break;case "shared":f+=this.Class.path.shared;break;case "publisher":f+="/content/"+e(this.config.app.publisher)+"/assets/"}a=a||"applets";switch(a.toLowerCase()){case "layouts":f+="layouts/";break;case "applets":f+="applets/";break;case "scripts":f+="js/";break;case "styles":f+="css/";break;case "images":f+="img/";break;case "sounds":f+="snd/";break;case "libraries":f+="lib/"}"publisher"==b&&!0==c&&a&&(f+=e(this.config.app.name)+"/");return f},parseConfigFiles:function(){var a=
["publisher","shared","vendor"],b=["styles","scripts","applets","libraries"],c=[],e;self=this;$res=this.config.files;try{this.filesNeeded=[],b.forEach(function(b){"undefined"!=typeof $res[b]&&a.forEach(function(a){e=$res[b][a];if("string"===typeof e&&0<e.length&&(e=$res[b][a].split(","),"object"===typeof e&&0<e.length))for(c=$res[b][a].split(","),i=0;i<c.length;i++)self.filesNeeded.push(self.getPath(b,a)+c[i])})})}catch(f){return this.error(f,_,Array.prototype.slice.call(arguments,0)),!1}return!0},
_onConfigSuccess:function(a){this.config||(this.config=JSON.parse(a));this.Class.configLoaded=!0;try{this.parseConfigFiles(this)&&(this.Class.filesLoaded=!0)}catch(b){return this.error(b,_,Array.prototype.slice.call(arguments,0)),!1}this.Class.ready=!0==this.Class.configLoaded&&!0==this.Class.filesLoaded;this._onSuccessCallback&&this._onSuccessCallback(this.filesNeeded)},_onConfigFailed:function(){!1==this.Class.ready;this._onFailedCallback&&this._onFailedCallback([])},get:function(a){(a=a||!1)&&
a.split(".")},set:function(a,b){},toString:function(){return void 0===this.Class?"I$ConfigManager":this.Class.fullName+" [id: "+(this.objectId||0)+"]"}},{},[]);
extend("I$Alias","I$CloudApplication",{maxTotalObjects:1,exposed:!1,noCacheString:"",predefined:"{!DATE} {!TIME} {!DATETIME} {!APPNAME} {!APPVERSION} {!COPYRIGHT} {!AUTHOR} {!APPLET|[name,loc[local|nanofw|vendor|publisher]]}".split(" "),_ATTRIBUTES:"role name version uuid layout skin shared target cols".split(" "),timer:null,layout:{repo:"i2tm",name:"starter"},config:null,$totalBytesLoaded:0,google:null,local:null,applets:null,game:null,launcher:null,test:null,ready:!1,readyCalled:!1,finished:!1,
scripts:[],toString:function(){return"I$CloudApplication Class"}},{init:function(){this._super();this.$loc=this.gfn(document.location.href);this.clientFS_exists()&&(this.local=P$.interfaces.Store.I$DeviceStorage.create(this.config.config.app));this.applets=create("I$AppletFactory");this.ha();this.ready=!0},setup:function(){this.info("nano Framework v1.0.0");this._super();this.initEvents();this.timer=P$.interfaces.Store.I$AccuTimer.create(-1,2,M$.bnd(this,this._onInterval),M$.bnd(this,this._onTimerDone));
this.config=create("I$ConfigManager",M$.bnd(this,function(a){this.scripts=a}),M$.bnd(this,function(a){}));this.getPath=this.config.getpath},onReady:function(){this._super();this.createMeta();this.getlayout();this.prepare();window.APP=this;this.google&&this.google.load();this.autoSizeACE();this.applets.scan();this.config.config.modules.gldl&&(this.launcher=create("I$Launcher"),this.game=create("I$GameEngine","wrapper"))},clientFS_exists:function(){try{return localStorage.setItem("maestro","maestro"),
localStorage.removeItem("maestro"),!0}catch(a){return!1}},template:function(){M$.gei("wrapper")},prepare:function(){this.skin=(this.colorOverride=M$.chk(this.local.getGlobalCfg("colorOverride"),!1))?M$.chk(this.local.getGlobalCfg("mySkin"),this.skin):M$.chk(this.local.getAppCfg("skin"),this.skin)},getlayout:function(){var a=this.config.config.app.layout;this.vld(a)&&-1!=a.indexOf("|")||(a="i2tm|starter");a=a.split("|");this.addFile(a[1]+".nano","layouts",a[0])},getFontSize:function(){var a;a=M$.gei("wrapper");
return this.vld(a)?(a=window.getComputedStyle(a,null).getPropertyValue("font-size"),parseFloat(a)):16},reviewResolution:function(){if((d=D$.documentElement.dataset)&&this.layout.isValid(d.layout))return this.appLayout=d.layout,"absolute-all"===this.appLayout?this.setResolution(window.innerWidth-400):this.setResolution()},initEvents:function(){$(window).resize(function(){clearTimeout(this.resizeTimer);this.resizeTimer=setTimeout(this._onResizeComplete,200)})},lockOrientation:function(){return"landscape"==
this.config.config.options.orientation||"portrait"==this.config.config.options.orientation?!0:!1},autoSizeACE:function(){var a,b;b=window.innerHeight-64;P$.interfaces.Core.isObject(window.ace)&&(a=M$.gei("ide"))&&(a.style.height=b+"px");P$.interfaces.Core.isObject(window.nanofm)&&(a=M$.gei("ide_fm"))&&(a.style.height=b+"px")},testOrientation:function(){!1!=this.lockOrientation()&&("landscape"==this.config.config.options.orientation?window.innerWidth>window.innerHeight?(M$.pld(),M$.off("page_warning"),
this.Class.appPaused=!1):(this.Class.appPaused=!0,M$.gei("orientation").innerHTML="Landscape",M$.ple(),M$.on("page_warning")):"portrait"==this.config.config.options.orientation&&(window.innerWidth<window.innerHeight?(M$.pld(),M$.off("page_warning"),this.Class.appPaused=!1):(this.Class.appPaused=!0,M$.gei("orientation").innerHTML="Portrait",M$.ple(),M$.on("page_warning"))))},forceRedraw:function(){M$.gei("wrapper").style.display="none";location.reload()},forceResize:function(){var a,b;-1!=navigator.appName.indexOf("Microsoft")?
(a=document.body.offsetWidth,b=document.body.offsetHeight):(a=window.outerWidth,b=window.outerHeight);window.resizeTo(a-1,b);window.resizeTo(a+1,b)},checkScreenMode:function(){var a=this.mode;721>window.innerWidth&&0!=a?this.mode=0:720<window.innerWidth&&961>window.innerWidth&&1!=a?this.mode=1:960<window.innerWidth&&1921>window.innerWidth&&2!=a?this.mode=2:1920<window.innerWidth&&3!=a&&(this.mode=3);this.mode!=a&&this._onScreenSizeChanged()},save:function(){this.local.setGlobalCfg("colorOverride",
this.colorOverride);this.local.setAppCfg("skin",this.skin)},addToHead:function(a,b,c){var e;"script"==a?(e=D$.createElement(a),e.id=b,e.type="application/javascript",e.innerHTML=c):"style"==a?(e=D$.createElement(a),e.id=b,e.type="text/css",e.innerHTML=c):this.warn("Attempting to add unknown element "+a+" to DOM.");$a=get("head")[0];$a=get("head")[0].appendChild(e)},createWindow:function(a,b){ISA(a);"object"!==ISA(b)&&(b={id:"window",height:"17.14em",width:"22.85em",title:"Unamed Window",statusbar:"",
body:"",color:"clr-dark"});var c=DOC.createElement("div");c.id=b.id;c.className="this_window "+b.color;$html='<div class="this_window.this_titleBar">\n';$html+='<div class="this_title left"><span id="windowName">'+$title+"</span></div>\n";$html+='<div class="icons right">\n';$html+='<i class="icon icon-move uiButton"></i>\n';$html+='<i class="icon icon-collapse-alt uiButton"></i>\n';$html+='<i class="icon icon-expand-alt uiButton"></i>\n';$html+="</div>\n";$html+="</div>\n";$html+='<div id="windowBody" class="this_body">'+
$body+"</div>\n";$html+='<div class="this_statusBar">\n';$html+='<div id="windowStatusBar">'+$status+"</div>\n";$html+="</div>\n";c.innerHTML=$html},setDisableCache:function(){this.Class.noCacheString=M$.isDevMode()?"?nocache="+Date.now():""},addFile:function(a,b,c){this.scripts.push(this.config.getPath(b,c)+a)},que:function(a,b,c){for(var e=0,e=0;e<a.length;e++)this.addFile(a[e],b,c)},compile:function(a){return lzw.enc(encodeURIComponent(a))},decompile:function(a){return lzw.dec(encodeURIComponent(a))},
validUUID:function(a){if(this.vld(a)&&""!==a&&4==a.split("-").length-1){if("1"==a.charAt(4)&&"9"==a.charAt(17)&&"6"==a.charAt(22)&&"9"==a.charAt(30))return!0;if("file:"===location.protocol&&M$.getDevMode())return this.error("Validation Failed, Bad UUID!"),!1}},generateUUID:function(){return"xxxx1xxx-xxxx-4xx9-yxx6-xxxxxx9xxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})},redraw:function(){var a=D$.getElementsByTagName("body")[0];a.style.display="none";
a.offsetHeight=a.offsetHeight;a.style.display="block"},addMeta:function(a,b){try{var c={el:null,head:H$};c.head.contains(a)||(c.el=D$.createElement("meta"),c.el.id=c.el.name=a,c.el.content=b,c.head.appendChild(c.el))}catch(e){M$.err(this,e,c,Array.prototype.slice.call(arguments,0))}},createMeta:function(){this.addMeta("description",this.config.config.app.description);this.addMeta("author",this.config.config.app.author);this.addMeta("keywords",this.config.config.app.keywords);this.addMeta("copyright",
this.config.config.app.copyright)},ha:function(a,b,c,e,f,g,h){},ga:function(a,b,c,e,f,g,h){this.google&&this.google.ga(a,b,c,e,f,g,h)},_onScreenSizeChanged:function(){},_onResizeComplete:function(){if(this.google.$adSenseLoaded)this.google.onResize();this.autoSizeACE();this.testOrientation()},_onFullscreenChange:function(){var a=M$.gei("waCANVAS");document.mozFullScreen||document.webkitIsFullScreen?(a.style.width=window.screen.width+"px",a.style.height=window.screen.height+"px"):(a.style.width=this.config.screen.width+
"px",a.style.height=this.config.screen.height+"px")},onLayoutLoaded:function(a){this.gei("wrapper").innerHTML=a},_onLoaded:function(a,b){var c={};if(this.vld(b))if(c.ext=M$.gex(b),c.path,c.fileName=M$.gfn(b),c.parts=b.split("?"),c.size=a.length,""===c.fileName)this.warn("Invalid Ajax URI received: "+b);else if(this.$totalBytesLoaded+=c.size,1==c.parts.length?c.path=b.substring(b.lastIndexOf("/")+1):(c.ext=M$.gex(c.parts[0]),c.path=c.parts[0].substring(0,c.parts[0].lastIndexOf("/"))),"modernizr.min.js"==
c.fileName){var e=D$.createElement("script");e.id="modernizr";e.type="application/javascript";e.text="\n\r/* "+c.fileName+" */\n\r"+a;M$.get("head")[0].appendChild(e)}else if("nano"===c.ext)this.onLayoutLoaded(a);else if("css"===c.ext){e=D$.createElement("style");e.id=c.fileName;e.rel="stylesheet";e.type="text/css";e.media="all";e.textContent=".define_"+c.fileName+"\n\r"+a;try{M$.get("head")[0].appendChild(e)}catch(f){c.args=Array.prototype.slice.call(arguments,0),M$.err(this,f,c,Array.prototype.slice.call(arguments,
0))}}else if("js"===c.ext){e=D$.createElement("script");e.id=c.fileName;e.type="application/javascript";e.text=a;try{M$.gei("tail").appendChild(e)}catch(g){c.args=Array.prototype.slice.call(arguments,0),M$.err(this,g,c,Array.prototype.slice.call(arguments,0))}}},_onErrored:function(a){},_onInterval:function(a,b,c){0<this.scripts.length?(this.finished=!1,a=this.scripts.shift(),M$.xhr(a,this._onLoaded.bind(this),this._onErrored.bind(this),"get",null,!1)):(this.finished=!0,this.google&&this.google.loaded());
this.finished&&this.ready&&!this.readyCalled&&("function"===typeof window.nanoREADY&&window.nanoREADY(),this.readyCalled=!0,M$.pld())},_onTimerDone:function(a){this.finished||(this.info("Unable to load & initialize application within 15 seconds, aborting."),alert("Unable to load & initialize application within 15 seconds, aborting."));M$.pld()},toString:function(){return void 0===this.Class?"I$CloudApplication":this.Class.fullName+" [id: "+(this.objectId||0)+"]"}},{},[]);
